In [1]:
# We'll cover:

# 1) Indexing and Slicing 
# 2) Iterating through arrays
# 3) Stacking together two arrays
# 4) Indexing with boolean arrays

# Indexing and Slicing 

In [2]:
import numpy as np

In [5]:
n = np.array([6,7,8])
n

array([6, 7, 8])

In [6]:
n[0:2]

array([6, 7])

In [7]:
n[-1]

8

In [8]:
# Multi-dimensional array
a = np.array([[6,7,8], [1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [9]:
# Look at the arrangement of Rows and columns
a[1,2]

3

In [10]:
a[0:2, 2]

array([8, 3])

In [18]:
# It is the last element in the row
a[-1]

array([9, 3, 2])

In [13]:
a[-1, 0:2]

array([9, 3])

In [17]:
# Now let's say you want to print [7,2,3] and [8,3,2]
# Syntax for going through the rows is:

a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

# Iterating through arrays



In [19]:
a = np.array([[6,7,8], [1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [24]:
for rows in a:
  print(rows)

[6 7 8]
[1 2 3]
[9 3 2]


In [25]:
# Sometimes you want to flatten the list and print every cell
for cell in a.flat:
  print(cell)

# What this is doing is falttening the arrays as if everything is a single element

6
7
8
1
2
3
9
3
2


# Stacking together two arrays

In [26]:
# WHat I am doing here is making an array of range 1,6 but 6 is not included and the shape I'm giving is 3 rows and 2 clomuns
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [28]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [30]:
# If you want to VERTICALLY stack them together, just imagine the two arrays as box and as if you're making a whole complete box
np.vstack((a,b))
# So as you see, it kinda stack them together (both of the arrays) as a one whole box

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [31]:
# Now let's say you want to HORIZONTALLY stack them together
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [32]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [37]:
# Now if you want to split this array into 3 different arrays (IMAGINE you're VERTICALLY slicing them into 3 different equal size arrays)
np.hsplit(a,3)
# It needs to be EQUAL DIVISION

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [43]:
# It's hard to visualize the result so let me show you an easier way to visualize it
result = np.hsplit(a,3)

In [42]:
# ARRAY 1
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [39]:
# ARRAY 2
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [40]:
# ARRAY 3
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [46]:
 n = np.vsplit(a,2)
 n

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [47]:
n[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [48]:
n[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# Indexing with boolean arrays

In [50]:
# ALways use this way of making arrays in NumPy as it saves your time and is really easy-to-understand
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
# Let's say I have this b (variable) an I say that (b = a > 4) , what is going to happeen it that it's gonna create another NumPy array and store the result of this 
# expression into individual elements
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [53]:
# Basically it's gonna print the values of b in the array which are greater than 4
# SO it looked at the array for the values b which are greater than 4 and retuened it with us in the output
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
# This is a cool way of extracting all the elements which are greater than 4 from your original array

In [55]:
# This is also useful if you want to replace those elements with a certain number that are greater than 4 
a[b] = -1
a
# Any element that was greater than 4 was replaced with {-1}
# This could be really poerful depending on what kind of application you're writing

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])