### NumPy vs Python
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

### NumPy list vs Python list
The main difference is that NumPy arrays are much faster and have strict requirements on the homogeneity of the objects. For example, a NumPy array of strings can only contain strings and no other data types, but a Python list can contain a mixture of strings, numbers, booleans and other objects.

NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original. The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

There are two main reasons why we would use NumPy array instead of lists in Python. These reasons are: Less memory usage: The Python NumPy array consumes less memory than lists. Less execution time: The NumPy array is pretty fast in terms of execution, as compared to lists in Python.

In [7]:
import numpy as np
import sys
import time

In [8]:
 NumPy = np.array([1,2,3])

In [9]:
NumPy

array([1, 2, 3])

In [10]:
NumPy[0]

1

In [11]:
NumPy[1]

2

I already have a Python list, why do I need this NumPy Array?
Well there are 3 main beenfits of using NumPy Array:
* Less Memory
* Fast
* Convinient

We'll prove them in this lecture

## Why Numpy Array uses Less memory than Python lis?
## Proof:

In [30]:
# So we have a Python list here and we need to get the size of 1 element, it doesn't matter what you write in the brackets, could be 1 or 5 as
# you're reffering to any element between 1,1000
# So basically size of 1 element multiplied by the length of the list 
python_list = range(1000)
print(sys.getsizeof(1)*len(python_list))

# Now we are going to create a NumPy array
# arange is similar to range 
# array.itemsize is size of one element vs array of size is equal to toal length of an array
numpy_array = np.arange(1000)
print(numpy_array.size*numpy_array.itemsize)

# Python list is taking 28,000 bytes vs NumPy is taking only 4000 bytes
# the size of one python object is like 28 here vs size on one NumPy array abject here in this case it is only 4 bytes


28000
4000


## Why numpy array is fast
## Proof:

In [24]:
# So I'm making Python lists and NumPy array's here 
size_of_list = 1000000

python_list_1 = range(size_of_list)
python_list_2 = range(size_of_list)

numpy_array_1 = np.arange(size_of_list)
numpy_array_2 = np.arange(size_of_list)

# Now I want to measure the time between Python list processing and NumPy array processing
start = time.time()
# So the opreation I'm doing here is adding the two Python lists and adding it to a new variable called result
# Zip will basically take first element from python_list_1 and first element from python_list_2 and add them together and put it in the result.
# So it'll add indivudal elements from these two lists and put it in a result
for x,y in zip(python_list_1, python_list_2):
    result = x+y
#---------------------------Python List processing time--------------------------------------
#We are multiplying by 1000 by default it's in second and I want to print milliseconds
print('Python list took this much time', (time.time()-start)*1000)
#---------------------------NumPy Array Processing time--------------------------------------
# NumPy is convenient so if you want to add two array you can just add it directly
start = time.time()
result = numpy_array_1 + numpy_array_2
print("NumPy array took this much time", (time.time()-start)*1000)

#  this code block {time.time()-start)*1000} is just way to measure time

# Now you can see Python list took about 150 milliseconds vs NumPy array to about  1.9 milliseconds
# This is CRAZY FAST!
# So you can see when you're processing millions and billions of numbers, it just makes sense of NumPy array 
# It is also conveneint becuase you can see that if you want to add to lists together you, can just di it like Maths!

Python list took this much time 150.1598358154297
NumPy array took this much time 1.9917488098144531


## Why NumPy is conveneint?

In [31]:
numpy_array_1  = np.array([1,2,3])
numpy_array_2  = np.array([4,5,6])

In [32]:
# Addition
numpy_array_1 + numpy_array_2

array([5, 7, 9])

In [33]:
# Subtraction
numpy_array_2-numpy_array_1

array([3, 3, 3])

In [34]:
# Multiplication
numpy_array_1*numpy_array_2

array([ 4, 10, 18])

In [35]:
# Division
numpy_array_1/numpy_array_2

array([0.25, 0.4 , 0.5 ])